= Table.UnpivotOtherColumns(#"Tipo Alterado1", {"Tipo", "Componente"}, "Data", "Valor")

esse passo serve para quando mesmo depois de transposta linha x coluna, não resolveu o problema de resumo e/ou clusterização dos dados.

Sua empresa deseja ter uma visão das receitas e despesas e solicitou que você criasse um 
Dashboard que permita analisar os seguintes indicadores financeiros:
1- Total de Receitas
2- Total de Despesas
3- Margem de Lucro
4- Total de Receitas Por Componente
5- Total de Despesas Por Componente em relação à média de Despesas
6- Total de Receitas e Despesas Por Componente e Por Ano, com a hierarquia 
Tipo/Componente.
Além disso a empresa precisa identificar os segmentos onde Receitas e Despesas são 
maiores e menores a fim de traçar seu plano estratégico.